#!/usr/bin/env bash
# Generates a local-only .csproj so the C# extension/OmniSharp has something
# to load against Assets/Scripts/*.cs in this Codespace.
#
# Important limitation: this project has no reference to UnityEngine.dll /
# UnityEditor.dll (those only exist inside a real Unity install), so this
# gives plain C#-language IntelliSense (syntax, base class library) — NOT
# Unity API completion (MonoBehaviour, GameObject, etc. will show as
# unresolved here). Full Unity-aware IntelliSense requires opening the
# project in the actual Editor on the other machine.
#
# Newtonsoft.Json is pinned to 13.0.2 because that's the version Unity's
# com.unity.nuget.newtonsoft-json package (3.2.x) bundles. That package must be
# added on the Editor machine for the roster loader to compile there.
#
# *.csproj is gitignored (standard Unity .gitignore) because Unity
# regenerates its own on the Editor machine — this file is disposable and
# never committed. It's rewritten on every run so changes here reach
# existing Codespaces, not just new ones.
set -euo pipefail
cd "$(dirname "$0")/.."

CSPROJ="Assets/Scripts/SideQuest.Scripts.csproj"
mkdir -p Assets/Scripts

cat > "$CSPROJ" <<'EOF'
<!--
  Local-only IntelliSense aid, NOT the real Unity-generated project file.
  Regenerated by .devcontainer/setup-intellisense.sh; gitignored on purpose.
  Provides plain C# language tooling for files in this folder — no
  UnityEngine/UnityEditor references are available in this environment.
-->
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>9.0</LangVersion>
    <EnableDefaultCompileItems>true</EnableDefaultCompileItems>
    <Nullable>disable</Nullable>
    <NoWarn>CS0246</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.2" />
  </ItemGroup>
</Project>
EOF

echo "Wrote $CSPROJ"
