#!/usr/bin/env bash
# Generates a local-only .csproj so the C# extension/OmniSharp has something
# to load against Assets/Scripts/*.cs in this Codespace.
#
# Important limitation: this project has no reference to UnityEngine.dll /
# UnityEditor.dll (those only exist inside a real Unity install), so this
# gives plain C#-language IntelliSense (syntax, base class library) — NOT
# Unity API completion (MonoBehaviour, GameObject, etc. will show as
# unresolved here). Full Unity-aware IntelliSense requires opening the
# project in the actual Editor on the other machine.
#
# *.csproj is gitignored (standard Unity .gitignore) because Unity
# regenerates its own on the Editor machine — this file is disposable,
# regenerated on every container create, and never committed.
set -euo pipefail
cd "$(dirname "$0")/.."

CSPROJ="Assets/Scripts/SideQuest.Scripts.csproj"
mkdir -p Assets/Scripts

if [ -f "$CSPROJ" ]; then
  echo "IntelliSense project already exists at $CSPROJ, leaving it alone."
  exit 0
fi

cat > "$CSPROJ" <<'EOF'
<!--
  Local-only IntelliSense aid, NOT the real Unity-generated project file.
  Regenerated by .devcontainer/setup-intellisense.sh; gitignored on purpose.
  Provides plain C# language tooling for files in this folder — no
  UnityEngine/UnityEditor references are available in this environment.
-->
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>9.0</LangVersion>
    <EnableDefaultCompileItems>true</EnableDefaultCompileItems>
    <Nullable>disable</Nullable>
    <NoWarn>CS0246</NoWarn>
  </PropertyGroup>
</Project>
EOF

echo "Wrote $CSPROJ"
